### ISSUE TITLE
PHP fatal error on model creation

### ISSUE THREAD

**Issue by joeljuca** [alterfw/hero#13]
I'm getting the following error while trying to create a model:

``` sh
src❯ ./vendor/bin/hero create:model highlight
PHP Fatal error:  Call to undefined function Hero\add_action() in /Users/joel/Projetos/Pessoais/bipmed-wp/src/vendor/alterfw/hero/bootstrap/loader.php on line 70
```

The line 70 of file `loader.php` contains the following function call:

``` php
<?php namespace Hero;

// (...) Code not related to the issue (...)

add_action( 'save_post', function($post_id) {
  $className = ucfirst(get_post_type($post_id));
  if(class_exists($className))
    call_user_func_array($className.'::saved', [$post_id]);
});
```

I'm not sure why it's happening but I'm betting that, due to the namespace definition, PHP  consider that function to be a Hero class method function instead of a WordPress global procedure function. I tried to call it as `\add_action()` but it still doesn't work. I was also trying to find where do Hero loads the WordPress classes, functions, etc., but I couldn't find it at all.

My folder structure is:

```
./ (Project folder)
  ./www (WordPress folder)
    ./www/wp-content
      ./www/wp-content/themes
        ./www/wp-content/themes/bpm (symlink to ../../../src)
  ./src (WordPress theme folder - including Alter, Hero, etc.)
```

**Comment by sergiopvilar** [comment]
@joelwallis Thanks for reporting! Please run a `composer update` and  all should be good.
